---
spring.config.active.on-profile: locd
spring.prifiles.active: locd
spring.main.allow-bean-definition-overriding: true
logging.config: classpath:log/logback-locd.xml

domain:
    chat: //localhost:8423
    image: //image.xodud1202.kro.kr/publist/HDD1/Media/nas/upload/common

nas:
    ftp:
        host: xodud1202.ipdisk.co.kr
        port: 5021
        username: xodud1202
        pwd: tmd1202wls
        upload.path: /HDD1/Media/nas/upload/common
        temp.upload.path: /HDD1/Media/nas/upload/common/temp

upload:
    default:
        target.path: /WIDE/workspace/files/data/nas
        max.size: 10
        allow.extension: jpg|gif|jpeg|png|bmp|txt|doc|docx|ppt|pptx|xls|xlsx|hwp|pdf|mp4
        view: //image.xodud1202.kro.kr/publist/HDD1/Media/nas/upload/common
    goods:
        target.path: /WIDE/workspace/files/data/nas
        max.size: 10
        allow.extension: jpg|gif|jpeg
        view: //image.xodud1202.kro.kr/publist/HDD1/Media/nas/upload/common
    image:
        target.path: /WIDE/workspace/files/data/nas
        max.size: 10
        allow.extension: jpg|gif|jpeg|png
        view: //image.xodud1202.kro.kr/publist/HDD1/Media/nas/upload/common
    excel:
        target.path: /WIDE/workspace/files/data/nas/excel
        max.size: 10
        allow.extension: xls|xlsx
        view: //image.xodud1202.kro.kr/publist/HDD1/Media/nas/upload/common
    sample:
        target.path: /WIDE/workspace/files/data/nas/sample
        max.size: 10
        allow.extension: txt|doc|docx|ppt|pptx|xls|xlsx|hwp|pdf
        view: //image.xodud1202.kro.kr/publist/HDD1/Media/nas/upload/common

download.path: /WIDE/workspace/files/data/nas